using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BeatSaberSongDownloader
{
    internal class BSaberSearchFilterEnums
    {
        public enum Time
        {
            [CustomName("all")]
            All,
            [CustomName("3-months")]
            Months3,
            [CustomName("30-days")]
            Days30,
            [CustomName("7-days")]
            Days7,
            [CustomName("24-hours")]
            Hours24
        }

        public enum Genre
        {
            [CustomName("all")]
            AllGenres,
            [CustomName("00s")]
            ZeroZeros,
            [CustomName("map-style")]
            MapStyle,
            [CustomName("balanced")]
            Balanced,
            [CustomName("dance-style")]
            DanceStyle,
            [CustomName("fitness")]
            Fitness,
            [CustomName("tech")]
            Tech,
            [CustomName("speed")]
            Speed,
            [CustomName("accuracy")]
            Accuracy,
            [CustomName("difficulty")]
            Difficulty,
            [CustomName("novice")]
            Novice,
            [CustomName("intermediate")]
            Intermediate,
            [CustomName("advanced")]
            Advanced,
            [CustomName("master")]
            Master,
            [CustomName("360")]
            ThreehundredSixtees,
            [CustomName("60s")]
            Sixtees,
            [CustomName("70s")]
            Seventys,
            [CustomName("80s")]
            Eightys,
            [CustomName("90")]
            NinetyDegrees,
            [CustomName("90s")]
            Ninetys,
            [CustomName("alternative")]
            Alternative,
            [CustomName("ambient")]
            Ambient,
            [CustomName("anime")]
            Anime,
            [CustomName("arabic")]
            Arabic,
            [CustomName("audica")]
            Audica,
            [CustomName("beastMap")]
            BeastMap,
            [CustomName("blues")]
            Blues,
            [CustomName("characteristic")]
            Characteristic,
            [CustomName("christian")]
            Christian,
            [CustomName("chroma")]
            Chroma,
            [CustomName("cinema-mod")]
            CinemaMod,
            [CustomName("classical-orchestral")]
            ClassicalAndOrchestral,
            [CustomName("comedy-meme")]
            ComedyAndMeme,
            [CustomName("community-playlists")]
            CommunityPlaylists,
            [CustomName("Country")]
            Country,
            [CustomName("Curators")]
            Curators,
            [CustomName("Dance")]
            Dance,
            [CustomName("Decade")]
            Decade,
            [CustomName("Disco")]
            Disco,
            [CustomName("drum-and-bass")]
            DrumAndBass,
            [CustomName("dubstep")]
            Dubstep,
            [CustomName("effect")]
            Effect,
            [CustomName("electro-house")]
            ElectroHouse,
            [CustomName("electronic")]
            Electronic,
            [CustomName("experience-map")]
            ExperienceMap,
            [CustomName("folk-acoustic")]
            FolkAndAcoustic,
            [CustomName("funk-disco")]
            FunkAndDisco,
            [CustomName("genre")]
            Genre,
            [CustomName("german")]
            German,
            [CustomName("hardcore")]
            Hardcore,
            [CustomName("hip-hop-rap")]
            HipHopAndRap,
            [CustomName("holiday")]
            Holiday,
            [CustomName("house")]
            House,
            [CustomName("indie")]
            Indie,
            [CustomName("instrumental")]
            Instrumental,
            [CustomName("interview")]
            Interview,
            [CustomName("j-pop")]
            JPop,
            [CustomName("j-rock")]
            JRock,
            [CustomName("japanese")]
            Japanese,
            [CustomName("jazz")]
            Jazz,
            [CustomName("k-pop")]
            KPop,
            [CustomName("kids-family")]
            KidsAndFamily,
            [CustomName("korean")]
            Korean,
            [CustomName("language")]
            Language,
            [CustomName("latin")]
            Latin,
            [CustomName("mapper")]
            Mapper,
            [CustomName("mashup")]
            Mashup,
            [CustomName("metal")]
            Metal,
            [CustomName("mod")]
            Mod,
            [CustomName("modchart")]
            Modchart,
            [CustomName("musical")]
            Musical,
            [CustomName("news")]
            News,
            [CustomName("nightcore")]
            Nightcore,
            [CustomName("no-arrows")]
            NoArrows,
            [CustomName("official-playlists")]
            OfficialPlaylists,
            [CustomName("one-saber")]
            OneSaber,
            [CustomName("other-rhythm-games")]
            OtherRhythmGames,
            [CustomName("plugins")]
            Plugins,
            [CustomName("pop")]
            Pop,
            [CustomName("post-hardcore")]
            PostHardcore,
            [CustomName("punk")]
            Punk,
            [CustomName("quest")]
            Quest,
            [CustomName("rb")]
            RAndB,
            [CustomName("reggae")]
            Reggae,
            [CustomName("rock")]
            Rock,
            [CustomName("soul")]
            Soul,
            [CustomName("speedcore")]
            Speedcore,
            [CustomName("swing")]
            Swing,
            [CustomName("techno")]
            Techno,
            [CustomName("trance")]
            Trance,
            [CustomName("tutorials")]
            Tutorials,
            [CustomName("tv-movies")]
            TVAndMovies,
            [CustomName("Uncategorized")]
            Uncategorized,
            [CustomName("video-game")]
            VideoGame,
            [CustomName("videos")]
            Videos,
            [CustomName("vocaloid")]
            Vocaloid
        }
    }
}
